changelog:
  categories:
    - title: Features
      labels: 
        - feat
        - feature
        - enhancement
    - title: Bug Fixes
      labels: 
        - bug
        - fix
        - bugfix
    - title: Misc
      labels:
        - chore
        - misc
        - other